name: Auto PR to main

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR using GitHub CLI
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Auto PR from ${{ github.ref_name }}" \
            --body "This PR was automatically created on push to ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
