name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create-auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: DEBUG - Cek branch dan status
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          git status
          git branch -a
          git log --oneline -n 5
          echo "Remote info:"
          git remote -v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR: Merge ${{ github.ref_name }} to main"
          commit-message: "Auto PR created from ${{ github.ref_name }}"
          base: main
          branch: ${{ github.ref_name }}
          draft: false
          create-when-empty: true
