name: Check Changed Files

on:
  push:
    branches-ignore:
      - main

jobs:
  check-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch the latest changes from the remote repository
      - name: Fetch latest changes
        run: git fetch origin

      # Step 3: Get list of changed files
      - name: Get Changed Files
        id: get_files
        run: |
          # Get the list of files changed between the current commit and origin/main
          echo "Changed files:"
          files=$(git diff --name-only origin/main)
          echo "$files"
          echo "::set-output name=changed_files::$files"

      # Step 4: Display changed files in the log
      - name: Display Changed Files
        run: |
          echo "Files that have changed or were added in the latest commit:"
          echo "${{ steps.get_files.outputs.changed_files }}"
