name: Auto PR to main

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create pull request
        uses: peter-evans/pull-request@v3
        with:
          source: ${{ github.ref_name }}
          target: main
          title: "Auto PR from ${{ github.ref_name }}"
          body: "This PR was created automatically after push to ${{ github.ref_name }}."
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
