name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH.PAT }}
          title: "Auto PR: Merge ${{ github.ref_name }} to main"
          commit-message: "Auto PR created from ${{ github.ref_name }}"
          base: main
          branch: ${{ github.ref_name }}
          draft: false
          create-when-empty: true
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
