name: Auto PR with CodeBERT Analysis (Tahap 1)

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Jalankan Analisis Keamanan
        run: python codebert_analysis.py > codebert-analysis.log

      - name: Potong hasil analisis (max 100 baris)
        run: |
          echo "📊 Code Security Report (terpotong, lihat log lengkap di file)" > short-analysis.log
          head -n 100 codebert-analysis.log >> short-analysis.log

      - name: Buat Pull Request Otomatis
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Auto PR from ${{ github.ref_name }}" \
            --body-file short-analysis.log
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Full Log sebagai Artefak
        uses: actions/upload-artifact@latest
        with:
          name: codebert-full-log
          path: codebert-analysis.log

