name: Auto PR with CodeBERT Analysis 

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install transformers torch
          
      - name: Jalankan Analisis Keamanan
        run: python codebert_analysis.py > codebert-analysis.log

      - name: Potong hasil analisis (max 20 baris)
        run: |
          echo "📊 Ringkasan hasil analisis CodeBERT (log lengkap di artefak GitHub Action)." > short-analysis.log
          head -n 20 codebert-analysis.log >> short-analysis.log


      - name: Buat Pull Request Otomatis
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Auto PR from ${{ github.ref_name }}" \
            --body-file short-analysis.log
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Full Log sebagai Artefak
        uses: actions/upload-artifact@v4.6.2
        with:
          name: codebert-full-log
          path: codebert-analysis.log

