name: Auto PR with CodeBERT Analysis

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: git fetch origin

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install transformers torch huggingface_hub

      - name: Get changed files
        run: |
          git diff --name-only origin/main > changed_files.txt
          echo "📄 Changed files:"
          cat changed_files.txt

      - name: Run CodeBERT Analysis
        run: |
          python codebert_analysis.py changed_files.txt
          echo "REPORT_FILENAME=codebert-report.log" >> $GITHUB_ENV

      - name: Extract PR Summary
        run: |
          # Ambil bagian SUMMARY saja untuk PR comment
          sed -n '/\[\[SUMMARY]]/,/\[\[DETAILED FINDINGS]]/p' $REPORT_FILENAME | head -n -2 > pr-summary.log
          echo "Laporan lengkap tersedia di artifact" >> pr-summary.log

      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "CodeBERT Analysis: ${{ github.ref_name }}" \
            --body-file pr-summary.log
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Full Report
        uses: actions/upload-artifact@v4
        with:
          name: codebert-security-report
          path: ${{ env.REPORT_FILENAME }}
