name: Auto PR to main

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to main
        run: |
          gh pr create --base main --head ${{ github.ref_name }} --title "Auto PR from ${{ github.ref_name }}" --body "This is an automated pull request from branch ${{ github.ref_name }} to main." --draft=false
