name: Auto PR to main

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request to main
        uses: peter-evans/pull-request@v5
        with:
          source: ${{ github.ref_name }}
          target: main
          title: "Auto PR from ${{ github.ref_name }}"
          body: "This is an automated pull request from branch ${{ github.ref_name }} to main."
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          allow-existing-pr: true
