name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  block-direct-push:
    if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from a pull request
        run: |
          echo "❌ Direct push to 'main' is not allowed. Use Pull Request instead."
          exit 1
