name: Auto PR with CodeBERT Analysis

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: git fetch origin

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_autoPR.txt
          
      - name: Get changed files
        run: |
          git diff --name-only origin/main > changed_files.txt
          echo "📄 Changed files:"
          cat changed_files.txt

      - name: Run CodeBERT Analysis
        id: codebert
        run: |
          python codebert_analysis.py changed_files.txt
          echo "report_filename=codebert-report.log" >> $GITHUB_OUTPUT
          if grep -q "✅ Tidak ditemukan kerentanan" codebert-report.log; then
            echo "no_vuln=true" >> $GITHUB_OUTPUT
          fi

      - name: Extract PR Summary
        run: |
          sed -n '/\[\[SUMMARY]]/,/\[\[DETAILED FINDINGS]]/p' ${{ steps.codebert.outputs.report_filename }} | head -n -2 > pr-summary.log
          echo "Laporan lengkap tersedia di artifact" >> pr-summary.log

      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "CodeBERT Analysis: ${{ github.ref_name }}" \
            --body-file pr-summary.log
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
                    
      - name: Tambahkan Label jika Aman
        if: steps.codebert.outputs.no_vuln == 'true'
        run: |
          PR_NUMBER=$(gh pr view --json number -q '.number')
          gh pr edit $PR_NUMBER --add-label "safe-to-merge"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}


      - name: Upload Full Report
        uses: actions/upload-artifact@v4
        with:
          name: codebert-security-report
          path: ${{ steps.codebert.outputs.report_filename }}
