name: Main Branch Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
          echo ""
          echo "✅ Deploy complete!"
          echo "🌐 Cek perubahan Web di URL : https://codebert-test-e90f8.web.app/"
